name: emle

channels:
  - conda-forge

dependencies:
  - ambertools
  - ase
  - compilers
  - deepmd-kit
  - eigen
  - pip
  - pytorch
  - python
  - torchani
  - xtb-python
  - pip:
    - git+https://github.com/lab-cosmo/librascal.git#egg=rascal[complete]
