name: emle-sire

channels:
  - conda-forge
  - openbiosim/label/dev

dependencies:
  - ambertools
  - ase
  - deepmd-kit
  - loguru
  - openmm >= 8.1
  - nnpops
  - pip
  - psutil
  - pygit2
  - pytorch
  - python
  - pyyaml
  - sire
  - torchani
  - xtb-python
  - pip:
    - mace-torch
