name: mlmm

channels:
  - conda-forge

dependencies:
  - ambertools
  - ase
  - eigen
  - compilers
  - deepmd-kit
  - pip
  - pytorch-gpu >= 2.0
  - torchani
  - pip:
    - git+https://github.com/lab-cosmo/librascal.git#egg=rascal[complete]
