name: emle

channels:
  - conda-forge

dependencies:
  - ambertools
  - ase
  - compilers
  - deepmd-kit
  - eigen
  - pip
  - pytorch-gpu >= 2.0
  - python < 3.11
  - torchani
  - pip:
    - git+https://github.com/lab-cosmo/librascal.git#egg=rascal[complete]
