name: emle-sire

channels:
  - conda-forge
  - openbiosim/label/emle

dependencies:
  - ambertools
  - ase
  - compilers
  - deepmd-kit
  - eigen
  - loguru
  - openmm >= 8.1
  - pip
  - psutil
  - pybind11
  - pytorch
  - python < 3.11
  - pyyaml
  - sire
  - torchani
  - xtb-python
  - pip:
    - git+https://github.com/lab-cosmo/librascal.git
